---
- name: Install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
      - java-1.8.0-openjdk.x86_64
      - pexpect

- name: Create group
  group:
    name: "{{ appgrp }}"
    state: present

- name: Create user 
  user:
    name: "{{ appuser }}"
    group: "{{ appgrp }}"
    state: present

- name: Copy Kafka Tibico - {{ tibico_version }}
  copy:
    src: "files/{{ tibico_version }}.tar.gz"
    dest: "/tmp/"

- name: Extract Kafka tibico to "{{ install_dir }}"
  become: true
  unarchive:
    src: /tmp/{{ tibico_version }}.tar.gz
    dest: "/opt/"
    copy: no

- name: Move Dir /opt/tibico
  become: true
  command: cp -r '/opt/{{ tibico_version }}/opt/tibco/.' '/opt/tibco'

- name: Remove Existing Tarball
  become: true
  file:
    state: absent
    path: /tmp/{{ tibico_version }}.tar.gz

- name: Remove Existing Tarball
  become: true
  file:
    state: absent
    path: '/opt/{{ tibico_version }}'

- include: tls-config.yaml


