- name: Create "{{ log_kafka_dir }}"
  become: true
  file: 
    path: "{{ log_kafka_dir }}"
    mode: 0750
    state: directory
  when: inventory_hostname in groups['kafka']

- name: Create "{{ apps_kafka_dir }}"
  become: true
  file: 
    path: "{{ apps_kafka_dir }}"
    mode: 0750
    state: directory
  when: inventory_hostname in groups['kafka']

- name: Copy server properties
  become: true
  template:
    src: server.properties.j2
    dest: "{{ config_dir }}/server.properties"
  when: inventory_hostname in groups['kafka']

- name: Copy client properties
  become: true
  template:
    src: client.properties.j2
    dest: "{{ config_dir }}/client.properties"
  when: inventory_hostname in groups['kafka']
  
- name: Copy Certs
  become: true
  copy:
    src:  "/tmp/certs.tar.gz"
    dest: "/tmp/"
#    remote_src: yes
  when: inventory_hostname in groups['kafka']

- name: Extract certs
  become: true
  unarchive:
    src:  "/tmp/certs.tar.gz"
    dest: "/tmp/"
  when: inventory_hostname in groups['kafka']

#- name: Create "{{ certificates }}"
#  become: true
#  file: 
#    path: "{{ certificates }}"
#    mode: 0750
#    state: directory
#  when: inventory_hostname in groups['kafka']

- name: Move Certs 
  become: true
  command: mv /tmp/certs '{{ certificates }}'
  when: inventory_hostname in groups['kafka']

- name: Create "{{ apps_kafka_dir }}"
  become: true
  file: 
    path: "{{ apps_kafka_dir }}"
    mode: 0750
    state: directory
  when: inventory_hostname in groups['kafka']

- name: Copy kafka service
  become: true
  template:
    src: kafka.service
    dest: /etc/systemd/system/
  when: inventory_hostname in groups['kafka']

- name: Copy jmx for prometheus
  copy:
    src: "../files/{{ jmxprometheus }}"
    dest: "{{ apps_kafka_dir }}"
  when: inventory_hostname in groups['kafka']

- name: Copy kafka template for prometheus
  copy:
    src: "../files/{{ kafkaprometheus }}"
    dest: "{{ apps_kafka_dir }}"
  when: inventory_hostname in groups['kafka']

- name: Update Permission Install Dir
  become: true
  file: 
    path: "{{ item }}"
    owner: "{{ appuser }}"
    group: "{{ appgrp }}"
    recurse: yes
    state: directory
  with_items:
    - "{{ apps_kafka_dir }}"
    - "{{ log_kafka_dir }}"

- name: systemd reload
  systemd:
    daemon_reload: yes
  when: inventory_hostname in groups['kafka']

#- name: restart_kafka
#  systemd:
#    name: kafka.service
#    state: restarted
#  when: inventory_hostname in groups['kafka']

#- name: enable_kafka
#  systemd:
#    name: kafka.service
#    enabled: yes
#  when: inventory_hostname in groups['kafka']

- name: Copy script create topic
  become: true
  template:
    src: createtopic.sh.j2
    dest: /tmp/createtopic.sh
  when: inventory_hostname in groups['kafka'][0]

#- name: Give permissions script file
#  file:
#    path: /tmp/createtopic.sh
#    owner: "{{ appuser }}"
#    group: "{{ appgrp }}"
#    mode: '0755'
#  when: inventory_hostname in groups['kafka'][0]

#- name: Create Topic
#  become: true
#  command: sh /tmp/createtopic.sh create
#  when: inventory_hostname in groups['kafka'][0]

#- name: create topic 
#  pause:  

#- name: Validate Topic
#  become: true
#  command: sh /tmp/createtopic.sh validar
#  when: inventory_hostname in groups['kafka'][0]

#- name: Validate topic 
#  pause:  