- name: Create {{ certdir_create }}
  become: true
  file: 
    path: "{{ certdir_create }}"
    mode: 0750
    state: directory
  when: inventory_hostname in groups['kafka'][0]

- name: Copy script tls generation
  become: true
  template:
    src: createcert.py.j2
    dest: "{{ certdir_create }}/createcert.py"
  when: inventory_hostname in groups['kafka'][0]

- name: Generate Cert 
  become: true
  shell: "(python createcert.py >/dev/null 2>&1 &)"
  args:
    chdir: "{{ certdir_create }}"
  async: 10
  poll: 0
  register: out
  when: inventory_hostname in groups['kafka'][0]

#- debug: var=out.stdout_lines
#  when: inventory_hostname in groups['kafka'][0]

- name: Aguardando a execucao do Certificado
  pause:  
    seconds: 10

- name: Wait until ok.cert
  wait_for:
    path: /tmp/certs/ok.cert
    state: present
  when: inventory_hostname in groups['kafka'][0]

- name: tar cert
  archive:
    path: "{{ certdir_create }}"
    dest: /tmp/certs.tar.gz
    format: gz
  when: inventory_hostname in groups['kafka'][0]

- name: Storing tar in ansible host tmp
  fetch:
    src: /tmp/certs.tar.gz
    dest: "/tmp/"
    flat: yes
  when: inventory_hostname in groups['kafka'][0]

- include: zookeeper-config.yaml